### ISSUE TITLE
unable to run it under windows

### ISSUE THREAD

**Issue by minikiller** [jumpman24/sgf-analyzer#29]
it works under linux but when i run it under windows,it show following error:
```
(.venv) PS D:\python-project\sgf-analyzer> python sgfanalyze.py .\2020-07-02.sgf --bot leela-zero
sgfanalyze.py:17: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_data = load(yaml_stream)
2020-07-03 09:49:03 INFO Found 1 sgf-files to analyze.
2020-07-03 09:49:03 INFO Started analyzing file: 2020-07-02.sgf
2020-07-03 09:49:03 INFO Started analyzing main line.
2020-07-03 09:49:03 INFO Executing analysis for 234 moves
2020-07-03 09:49:03 INFO Starting GTP...
2020-07-03 09:49:05 ERROR Exception during analysis.
Traceback (most recent call last):
  File "sgfanalyze.py", line 535, in run
    self.analyze_main_line()
  File "sgfanalyze.py", line 286, in analyze_main_line
    self.bot.start()
  File "D:\python-project\sgf-analyzer\bot_engines.py", line 121, in start
    self.send_command(f'boardsize {self.board_size}')
  File "D:\python-project\sgf-analyzer\bot_engines.py", line 83, in send_command
    self.process.stdin.flush()
OSError: [Errno 22] Invalid argument
2020-07-03 09:49:05 INFO Stopping GTP...
Traceback (most recent call last):
  File "sgfanalyze.py", line 575, in <module>
    game.run()
  File "sgfanalyze.py", line 544, in run
    self.bot.stop()
  File "D:\python-project\sgf-analyzer\bot_engines.py", line 135, in stop
    self.send_command('quit')
  File "D:\python-project\sgf-analyzer\bot_engines.py", line 83, in send_command
    self.process.stdin.flush()
OSError: [Errno 22] Invalid argument
```
this is my config files:
```
leela-zero:  # LeelaZero also requires weights
    bot_type: leela-zero
    executable: F:\\Tools\\go\\leela-zero-0.17-cpuonly-win64\\leelaz.exe
    arguments: --gtp --noponder --weights F:\\Tools\\go\\leela-zero-0.17-cpuonly-win64\\networks\\86fa6e9897785c5583de41a5cef4132eacb167c85e68e0f0bd063b75ae15ca58.gz

```

**Comment by minikiller** [comment]
it is my fault!
